[http]
    [http.middlewares]
        [http.middlewares.user-auth]
            [http.middlewares.user-auth.basicAuth]
                usersFile= "/etc/traefik/users"
        
        [http.middlewares.grafana-mw]
            [http.middlewares.grafana-mw.stripPrefix]
                prefixes = ["/grafana"]
                forceSlash = false
