secrets:
  portainer_admin_password:
    file: ${CONF_DIR}/portainer/secrets/portainer_admin_password

services:
  portainer:
    image: portainer/portainer-ce:${VPORTAINER}
    container_name: populo-portainer
    hostname: populo-portainer
    command:
      - '--admin-password-file=/run/secrets/portainer_admin_password'
      - '--no-analytics'
    ports:
      - "9000:9000"
    secrets:
      - portainer_admin_password
    security_opt:
      - "no-new-privileges:true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
  portainer:
